apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: mint-qa
  namespace: argocd

  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.devlake: devlake-webhook-success
    notifications.argoproj.io/subscribe.on-sync-failed.devlake: devlake-webhook-failure

spec:
  project: default

  sources:
    - repoURL: https://github.com/devops-champ/mint.git
      targetRevision: HEAD
      path: helm/app

      helm:
        valueFiles:
          - $values/mint/values/values-qa.yaml

    - repoURL: https://github.com/backstage2k26-cpu/gitops-nonprod.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: mint-qa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
