apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: inventory-service-qa
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://github.com/devops-champ/inventory-service.git
      targetRevision: 0.0.7
      path: helm/app

      helm:
        valueFiles:
          - $values/inventory-service/values/values-qa.yaml

    - repoURL: https://github.com/backstage2k26-cpu/gitops-nonprod.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: inventory-service-qa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
