apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ninja-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devops-champ/ninja.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - ../../values/ninja/values-qa.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ninja-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
