apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextking-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/devops-champ/nextking.git
      targetRevision: 0.0.3
      path: helm/app
      helm:
        valueFiles:
          - $values/nextking/values/values-dev.yaml
    - repoURL: https://github.com/backstage2k26-cpu/gitops-nonprod.git
      targetRevision: 0.0.3
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: nextking-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
