apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agrocd02-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devops-champ/agrocd02.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - ../../values/agrocd02/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: agrocd02-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
