apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: market-qa
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://github.com/devops-champ/market.git
      targetRevision: HEAD
      path: helm/app

      helm:
        valueFiles:
          - $values/market/values/values-qa.yaml

    - repoURL: https://github.com/backstage2k26-cpu/gitops-nonprod.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: market-qa

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
