apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: market-dev
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.devlake: devlake-webhook-success
    notifications.argoproj.io/subscribe.on-sync-failed.devlake: devlake-webhook-failure
spec:
  project: default
  sources:
    - repoURL: https://github.com/devops-champ/market.git
      targetRevision: v0.018
      path: helm/app
      helm:
        valueFiles:
          - $values/market/values/values-dev.yaml
    - repoURL: https://github.com/backstage2k26-cpu/gitops-nonprod.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: market-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
