apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nuxt-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/devops-champ/nuxt.git
      targetRevision: 0.0.5
      path: helm/app
      helm:
        valueFiles:
          - $values/nuxt/values/values-dev.yaml
    - repoURL: https://github.com/backstage2k26-cpu/gitops-nonprod.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: nuxt-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
